### ISSUE TITLE
Kuki Shinobu's image missing

### ISSUE THREAD

**Issue by peterwang1996** [PseudoMon/multilingual-genshin#1]
Kuki Shinobu's image is missing on both head and card, on website and repository

![image](https://user-images.githubusercontent.com/12966803/172130375-bf2b923e-096d-4934-9911-3693aabfc2c1.png)

**Comment by PseudoMon** [comment]
Oh wow I'm actually flattered someone bothered to report this as an issue! Thank you for being here!

Yes, I'm aware her images are missing. Her Talents and Constellations are still missing images too. Since she's not obtainable in-game yet, my usual sources don't have all relevant images for her yet. I can probably add them when Itto's banner is out, in about two weeks.

**Comment by peterwang1996** [comment]
OK, I got it.
And I want to thank you for awesome work in gathering all those text and images and makeing it public, it really helps a lot for people like me who are interested in those content. It would be great if you could keep working on it.
